/**
 * Per-fixture narration generator for the four map-video fixtures.
 *
 * For each fixture this script:
 *   1. Builds the scene schedule via `buildSceneSchedule(plan)`.
 *   2. Synthesizes per-scene voiceovers via `MockVoiceProvider`, falling back
 *      to a silent 16-bit PCM mono buffer of the scene's frame length when
 *      the scene has no `voiceoverText`.
 *   3. Concatenates the per-scene WAVs into a single narration track.
 *   4. Aligns caption lines to the scene schedule so the renderer can drive
 *      per-scene captions from a pre-computed plan.
 *   5. Writes the WAV, a JSON sidecar, and a generated TS module that the
 *      renderer package can import to wire `audioAsset`,
 *      `audioDurationSeconds`, and `captionLinesBySceneId`.
 *
 * Run from the repo root via:
 *   pnpm --filter @mapvideo/renderer exec tsx scripts/generate-narration.ts
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  alignSceneVoiceover,
  buildSceneSchedule,
  concatenateWavBuffers,
  encodeWav,
  MAP_VIDEO_FPS,
  MockVoiceProvider,
  type CaptionLine,
  type MapVideoPlan,
  countryZoomFixture,
  neutralMapVideoFixture,
  rankingFixture,
  rtlMapVideoFixture,
} from '@mapvideo/renderer';

/**
 * Remotion's default audio sample rate. `encodeWav` in the renderer package is
 * hardcoded to 44100 Hz, so the silent fallback below must match.
 */
const SAMPLE_RATE = 44100;

// ---------------------------------------------------------------------------
// Per-fixture generation
// ---------------------------------------------------------------------------

interface FixtureSpec {
  name: string;
  plan: MapVideoPlan;
}

const FIXTURES: readonly FixtureSpec[] = [
  { name: 'neutral', plan: neutralMapVideoFixture },
  { name: 'rtl', plan: rtlMapVideoFixture },
  { name: 'country-zoom', plan: countryZoomFixture },
  { name: 'ranking', plan: rankingFixture },
];

const provider = new MockVoiceProvider();

/**
 * Estimate a 16-bit PCM mono WAV buffer's duration in seconds. Mirrors
 * `estimateWavDurationSeconds` in @mapvideo/renderer/voice/wav.
 */
function estimateWavDurationSeconds(audioBuffer: ArrayBuffer): number {
  if (audioBuffer.byteLength < 44) return 0;
  const view = new DataView(audioBuffer);
  const byteRate = view.getUint32(28, true);
  if (byteRate === 0) return 0;
  const dataSize = view.getUint32(40, true);
  return dataSize / byteRate;
}

function sceneDurationSeconds(durationInFrames: number): number {
  return durationInFrames / MAP_VIDEO_FPS;
}

async function generateFixture(
  spec: FixtureSpec,
  audioOutputDir: string,
  generatedDir: string,
): Promise<void> {
  const schedule = buildSceneSchedule(spec.plan);

  const wavBuffers: ArrayBuffer[] = [];
  let totalDurationSeconds = 0;
  const captionLinesBySceneId: Record<string, CaptionLine[]> = {};

  for (let i = 0; i < spec.plan.scenes.length; i++) {
    const scene = spec.plan.scenes[i]!;
    const entry = schedule[i]!;
    const { startFrame, durationInFrames } = entry;
    const language = (scene.captionLanguage ?? 'en') as CaptionLanguage;
    const text = scene.voiceoverText?.trim() ?? '';

    if (text.length > 0) {
      const result = await provider.synthesize({ text, language });
      wavBuffers.push(result.audioBuffer);
      totalDurationSeconds += result.durationSeconds;
    } else {
      const sampleCount = Math.round(sceneDurationSeconds(durationInFrames) * SAMPLE_RATE);
      const silent = encodeWav(new Float32Array(sampleCount));
      wavBuffers.push(silent);
      totalDurationSeconds += estimateWavDurationSeconds(silent);
    }

    captionLinesBySceneId[scene.id] = alignSceneVoiceover(
      scene,
      language,
      startFrame,
      durationInFrames,
    );
  }

  const wavBuffer = concatenateWavBuffers(wavBuffers);
  const audioAssetRelative = `fixtures/narration/${spec.name}.wav`;
  const wavPath = path.join(audioOutputDir, `${spec.name}.wav`);
  const jsonPath = path.join(audioOutputDir, `${spec.name}.json`);

  writeFileSync(wavPath, Buffer.from(wavBuffer));
  writeFileSync(
    jsonPath,
    JSON.stringify(
      {
        fixtureName: spec.name,
        audioDurationSeconds: totalDurationSeconds,
        captionLinesBySceneId,
      },
      null,
      2,
    ),
  );

  // Generated TS — pinned to the spec from the brief. `as const` requires
  // a Record<string, CaptionLine[]> cast on the caption map (the value is
  // produced by JSON.stringify, so its static type widens to plain strings).
  const generatedTs = [
    '// Generated by scripts/generate-narration.ts. Do not edit by hand.',
    '',
    "import type { CaptionLine } from '@mapvideo/renderer/captions/types';",
    '',
    'export const generatedNarration = {',
    `  audioAsset: ${JSON.stringify(audioAssetRelative)},`,
    `  audioDurationSeconds: ${JSON.stringify(totalDurationSeconds)},`,
    `  captionLinesBySceneId: ${JSON.stringify(captionLinesBySceneId, null, 2)} as Record<string, CaptionLine[]>,`,
    '} as const;',
    '',
  ].join('\n');
  writeFileSync(path.join(generatedDir, `${spec.name}-narration.ts`), generatedTs);

  const displayPath = path.relative(process.cwd(), wavPath) || wavPath;
  console.log(
    `[narration] ${spec.name}: ${totalDurationSeconds.toFixed(2)}s across ${spec.plan.scenes.length} scenes → ${displayPath}`,
  );
}

async function main(): Promise<void> {
  // When invoked via `pnpm --filter @mapvideo/renderer exec tsx ...` the
  // process cwd is `packages/renderer`. Resolve paths from the script
  // location instead so the script works regardless of cwd. The script
  // lives at `<repo>/packages/renderer/scripts/...`, so three `..` hops
  // land on the repo root.
  const scriptDir = path.dirname(fileURLToPath(import.meta.url));
  const repoRoot = path.resolve(scriptDir, '..', '..', '..');
  const audioOutputDir = path.join(repoRoot, 'apps', 'remotion-studio', 'public', 'fixtures', 'narration');
  const generatedDir = path.join(repoRoot, 'packages', 'renderer', 'src', 'fixtures', 'generated');

  mkdirSync(audioOutputDir, { recursive: true });
  mkdirSync(generatedDir, { recursive: true });

  for (const spec of FIXTURES) {
    await generateFixture(spec, audioOutputDir, generatedDir);
  }
}

main().catch((err: unknown) => {
  console.error('Narration generation failed:', err);
  process.exit(1);
});
