import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  MockVoiceProvider,
  concatenateWavBuffers,
  alignCaptionsFromPlan,
  hashVoiceoverText,
  neutralMapVideoFixture,
  rtlMapVideoFixture,
  countryZoomFixture,
  rankingFixture,
  type MapVideoPlan,
} from '@mapvideo/renderer';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../../..');
const PUBLIC_DIR = path.resolve(ROOT, 'apps/remotion-studio/public/fixtures/narration');

/**
 * Fixtures that should receive generated narration audio and caption tracks.
 */
const FIXTURES: { name: string; plan: MapVideoPlan }[] = [
  { name: 'map-video-neutral', plan: neutralMapVideoFixture },
  { name: 'map-video-rtl', plan: rtlMapVideoFixture },
  { name: 'map-video-country-zoom', plan: countryZoomFixture },
  { name: 'map-video-ranking', plan: rankingFixture },
];

const provider = new MockVoiceProvider();

mkdirSync(PUBLIC_DIR, { recursive: true });

for (const { name, plan } of FIXTURES) {
  const language = plan.narration?.language ?? 'en';
  const voiceId = plan.narration?.voiceId ?? 'mock-default';
  const model = plan.narration?.model ?? 'mock-v1';

  const voiceoverTexts = plan.scenes
    .map((scene) => scene.voiceoverText?.trim())
    .filter((text): text is string => Boolean(text));

  if (voiceoverTexts.length === 0) {
    console.log(`⚠ ${name}: no voiceoverText found, skipping narration generation`);
    continue;
  }

  // Synthesize one WAV per scene and concatenate them into a single track.
  const sceneBuffers: ArrayBuffer[] = [];
  for (const text of voiceoverTexts) {
    const result = await provider.synthesize({ text, voiceId, provider: 'mock' });
    sceneBuffers.push(result.audioBuffer);
  }
  const combinedBuffer = concatenateWavBuffers(sceneBuffers);
  const audioFileName = `${name}.wav`;
  const audioPath = path.join(PUBLIC_DIR, audioFileName);
  writeFileSync(audioPath, Buffer.from(combinedBuffer));

  // Build a deterministic caption track from the plan.
  const captionTrack = alignCaptionsFromPlan(plan);
  const captionsFileName = `${name}.captions.json`;
  const captionsPath = path.join(PUBLIC_DIR, captionsFileName);
  writeFileSync(captionsPath, JSON.stringify(captionTrack, null, 2));

  const publicAudioAsset = `fixtures/narration/${audioFileName}`;

  // Update the fixture's generated narration config so the inline caption track
  // matches the freshly generated audio.
  const generatedSource = `// Generated by scripts/generate-map-video-narration.ts. Do not edit by hand.

import type { NarrationConfig } from '../../compositions/map-video/map-video-schema';

/**
 * Generated narration config for the ${name} fixture.
 *
 * Run \`pnpm generate:map-video-narration\` to regenerate audio and captions.
 */
export const generatedNarration: NarrationConfig = {
  provider: 'mock',
  voiceId: ${JSON.stringify(voiceId)},
  model: ${JSON.stringify(model)},
  language: ${JSON.stringify(language)},
  audioAsset: ${JSON.stringify(publicAudioAsset)},
  captions: ${JSON.stringify(captionTrack, null, 2)},
};
`;
  const generatedPath = path.resolve(
    ROOT,
    'packages/renderer/src/fixtures/generated',
    `${name}-narration.ts`,
  );
  writeFileSync(generatedPath, generatedSource);

  const fullText = voiceoverTexts.join(' ');

  console.log(
    `✓ ${name}\n` +
      `    audio: ${publicAudioAsset} (${(combinedBuffer.byteLength / 1024).toFixed(1)} KB)\n` +
      `    captions: ${publicAudioAsset.replace('.wav', '.captions.json')} (${captionTrack.lines.length} lines)\n` +
      `    text hash: ${hashVoiceoverText(fullText)}`,
  );
}
