import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { feature } from 'topojson-client';
import worldAtlas from 'world-atlas/countries-110m.json';
import worldCountries from 'world-countries';
import type { FeatureCollection, Geometry } from 'geojson';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rendererGeoDir = path.resolve(__dirname, '../src/geo');

interface CountryRecord {
  iso3: string;
  canonicalName: string;
  aliases: string[];
}

/**
 * Manual overrides for world-atlas names that do not match world-countries'
 * common name directly. World-atlas uses abbreviated Natural Earth labels.
 */
const isoOverrides: Record<string, string> = {
  'Bosnia and Herz.': 'BIH',
  'Central African Rep.': 'CAF',
  Congo: 'COG',
  "Côte d'Ivoire": 'CIV',
  'Dem. Rep. Congo': 'COD',
  'Dominican Rep.': 'DOM',
  'Eq. Guinea': 'GNQ',
  'Falkland Is.': 'FLK',
  'Fr. S. Antarctic Lands': 'ATF',
  Macedonia: 'MKD',
  'S. Sudan': 'SSD',
  'Solomon Is.': 'SLB',
  Turkey: 'TUR',
  'United States of America': 'USA',
  'W. Sahara': 'ESH',
};

const excludedNames = new Set(['N. Cyprus', 'Somaliland']);

function buildLookup(): Map<string, string> {
  const lookup = new Map<string, string>();
  for (const country of worldCountries) {
    const iso3 = country.cca3;
    const keys = [country.name.common, country.name.official, ...country.altSpellings];
    for (const key of keys) {
      const normalized = key.toLowerCase();
      if (!lookup.has(normalized)) {
        lookup.set(normalized, iso3);
      }
    }
  }
  return lookup;
}

function buildDictionary(): CountryRecord[] {
  const lookup = buildLookup();
  const countries = feature(
    worldAtlas,
    worldAtlas.objects.countries,
  ) as FeatureCollection<Geometry>;
  const records: CountryRecord[] = [];

  for (const f of countries.features) {
    const name = (f.properties?.name as string | undefined) ?? '';
    if (excludedNames.has(name)) {
      continue;
    }

    let iso3 = isoOverrides[name];
    if (!iso3) {
      iso3 = lookup.get(name.toLowerCase()) ?? '';
    }
    if (!iso3) {
      console.warn(`No ISO match for world-atlas country "${name}"`);
      continue;
    }

    records.push({
      iso3,
      canonicalName: name,
      aliases: [],
    });
  }

  records.sort((a, b) => a.canonicalName.localeCompare(b.canonicalName));
  return records;
}

function sha256File(filePath: string): string {
  const content = readFileSync(filePath);
  return createHash('sha256').update(content).digest('hex');
}

const dictionary = buildDictionary();
mkdirSync(rendererGeoDir, { recursive: true });
const dictionaryPath = path.join(rendererGeoDir, 'country-dictionary.json');
writeFileSync(dictionaryPath, JSON.stringify(dictionary, null, 2));
console.log(
  `Wrote ${dictionary.length} country records to ${path.relative(process.cwd(), dictionaryPath)}`,
);

const manifestPath = path.join(rendererGeoDir, 'dataset-manifest.ts');
const countriesChecksum = sha256File(
  path.resolve(__dirname, '../node_modules/world-atlas/countries-110m.json'),
);
const landChecksum = sha256File(
  path.resolve(__dirname, '../node_modules/world-atlas/land-110m.json'),
);

const manifestSource = `// Generated by scripts/prepare-geo-data.ts. Do not edit by hand.

/**
 * Geographic dataset provenance for deterministic vector map rendering.
 *
 * Data source: Natural Earth (public domain), packaged as\n * \`world-atlas@2.0.2\` (https://github.com/topojson/world-atlas).
 * ISO name mapping derived from the public-domain\n * \`world-countries@5.1.0\` list.
 */
export const GEO_DATASET = {
  source: 'Natural Earth',
  package: 'world-atlas',
  version: '2.0.2',
  resolution: '110m',
  license: 'Public domain (Natural Earth); package ISC (world-atlas)',
  countriesUrl: 'https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/countries-110m.json',
  landUrl: 'https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/land-110m.json',
  countriesSha256: '${countriesChecksum}',
  landSha256: '${landChecksum}',
  generatedAt: '${new Date().toISOString()}',
} as const;

export type GeoDataset = typeof GEO_DATASET;
`;

writeFileSync(manifestPath, manifestSource);
console.log(`Wrote dataset manifest to ${path.relative(process.cwd(), manifestPath)}`);
