import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rendererRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const manifestPath = path.join(rendererRoot, 'src/geo/dataset-manifest.ts');

function packageFilePath(specifier: string): string {
  return fileURLToPath(import.meta.resolve(specifier));
}

function sha256File(filePath: string): string {
  return createHash('sha256').update(readFileSync(filePath)).digest('hex');
}

function buildManifestSource(): string {
  const countriesChecksum = sha256File(packageFilePath('world-atlas/countries-110m.json'));
  const landChecksum = sha256File(packageFilePath('world-atlas/land-110m.json'));

  return `// Generated by scripts/prepare-geo-data.ts. Do not edit by hand.

/** Geographic dataset provenance for deterministic vector map rendering. */
export const GEO_DATASET = {
  source: 'Natural Earth',
  package: 'world-atlas',
  version: '2.0.2',
  resolution: '110m',
  license: 'Public domain geography; world-atlas package ISC',
  countriesPackagePath: 'world-atlas/countries-110m.json',
  landPackagePath: 'world-atlas/land-110m.json',
  countriesSha256: '${countriesChecksum}',
  landSha256: '${landChecksum}',
} as const;

export type GeoDataset = typeof GEO_DATASET;
`;
}

const expected = buildManifestSource();
const checkOnly = process.argv.includes('--check');

if (checkOnly) {
  const current = readFileSync(manifestPath, 'utf8');
  if (current !== expected) {
    throw new Error(
      'Geographic dataset manifest is stale. Run `pnpm geo:prepare` and commit the result.',
    );
  }
  console.log('Geographic dataset manifest is deterministic and current.');
} else {
  writeFileSync(manifestPath, expected);
  console.log(`Wrote ${path.relative(process.cwd(), manifestPath)}`);
}
